baseurl = "https://localhost:1313/" # Make sure to end baseurl with a '/'

languageCode = "en"
title = "Devops Mallu"
theme = "hemingway"
copyright = "&copy; <a href=\"https://github.com/imewish\">Vishnu Prassad</a> 2018"
disqusShortname = "shortname"
googleAnalytics = ""

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/tanksuzuki"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/tanksuzuki"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"


